### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by vladislav-tenishchev**
Good afternoon!
I would like to present some fixes for the library. In particular, fixing the duplication of the Dialer interface in the get_interfaces output, also for this interface, the ip address is now displayed. Also provided get_facts fixes for huawei AR and NE devices. If you consider including this pull request in the master branch, I would appreciate it. Thank you!

### CODE REVIEW

**Comment by codingnetworksb** [comment]
@vladislav-tenishchev thanks for being interested in improving this library. Can you share the command and the raw output that needed these fixes? I will use it to test your changes this weekend and merge if everything looks fine.

**Comment by vladislav-tenishchev** [comment]
@codingnetworksb 
Yes, sure. in the files ar outputs to observe the bug with Dialer interface, in the get_interfaces_ip output it did not parse the ip address from it. In the get_interfaces output, the Dialer1:0 interface was created, which is the internal state of the Dialer1 interface itself. The files ne, ar, ce also have outputs to check the get_facts output, now it outputs the model, serial numbers, uptime, software version not only for ce devices.
Also in the files there are outputs 'display interface' to check get_interfaces, in particular my fix to add parsing of speed from Eth-Trunk interfaces from AR,NE,CE devices. 

[ar_get_facts.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534289/ar_get_facts.txt)
[ar_get_interfaces.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534291/ar_get_interfaces.txt)
[ar_get_interfaces_ip.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534292/ar_get_interfaces_ip.txt)
[ce_get_facts.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534293/ce_get_facts.txt)
[ce_get_interfaces.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534294/ce_get_interfaces.txt)
[ne_get_facts.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534295/ne_get_facts.txt)
[ne_get_interfaces.txt](https://github.com/napalm-automation-community/napalm-huawei-vrp/files/12534296/ne_get_interfaces.txt)

If clarification is needed, I am always available to respond.

**Comment by codingnetworksb** [comment]
Hi @vladislav-tenishchev , this weekend i started to update the library because it was very outdated compared with original napalm library. I'm making sure it in complete compliance with getters structure, output, etc. I'm also implementing mocked data to for automatic testing when we make pull request. 

I couldn't review your pull request. I will do it as soon as i finish updating, hope during the week or weekend. And i'll let you know at that time to check the conflicts.

**Comment by codingnetworksb** [comment]
Hi @vladislav-tenishchev could you please check and fix the conflicts?

**Comment by vladislav-tenishchev** [comment]
Good afternoon, @codingnetworksb ! I'll get to it shortly

**Pull request closed without merging**
